String? nickName;
String? birth;
double? height;
double? weight;
double? bmr;
String? bmi;
String? gender;
int? age;
String? id;
String? token;
DateTime selectedDate = DateTime.now();
int userId = 1;
int? dday;
String? searchText;
List<String>? usedWidgets;
List<String>? unusedWidgets;
